import type { Project } from "@/types";

/**
 * Projects Data
 * Array of portfolio projects with detailed information
 */
export const projects: Project[] = [
  {
    id: "1",
    title: "3D Portfolio Website",
    description:
      "Interactive portfolio featuring cutting-edge 3D graphics and animations",
    longDescription:
      "A next-generation portfolio website built with Three.js, React Three Fiber, and Next.js. Features include particle systems, 3D models, smooth scrolling, and stunning visual effects. Optimized for performance with lazy loading and code splitting.",
    category: "3D Graphics",
    tags: ["Three.js", "React", "Next.js", "GSAP", "Framer Motion"],
    technologies: [
      "Next.js 15",
      "React 19",
      "Three.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
    ],
    image: "/projects/portfolio-3d.jpg",
    images: [
      "/projects/portfolio-3d-1.jpg",
      "/projects/portfolio-3d-2.jpg",
      "/projects/portfolio-3d-3.jpg",
    ],
    video: "/projects/portfolio-demo.mp4",
    liveUrl: "https://portfolio.example.com",
    githubUrl: "https://github.com/username/portfolio",
    featured: true,
    year: 2024,
    client: "Personal Project",
    role: "Full Stack Developer & 3D Artist",
    duration: "3 months",
    achievements: [
      "Lighthouse score: 95+",
      "50,000+ monthly visitors",
      "Featured on Awwwards",
    ],
    color: "#00F0FF",
  },
  {
    id: "2",
    title: "E-Commerce Platform",
    description:
      "Full-featured online store with payment gateway integration",
    longDescription:
      "Modern e-commerce platform with cart management, user authentication, payment processing via Stripe, order tracking, and admin dashboard. Built with scalability and security in mind.",
    category: "Web Development",
    tags: ["E-Commerce", "Full Stack", "Payment Gateway", "Admin Panel"],
    technologies: [
      "Next.js",
      "Node.js",
      "MongoDB",
      "Stripe",
      "Redux Toolkit",
      "Material-UI",
    ],
    image: "/projects/ecommerce.jpg",
    liveUrl: "https://shop.example.com",
    githubUrl: "https://github.com/username/ecommerce",
    featured: true,
    year: 2024,
    client: "Tech Retail Inc",
    role: "Lead Developer",
    duration: "4 months",
    achievements: [
      "Processed $500K+ in transactions",
      "10,000+ registered users",
      "99.9% uptime",
    ],
    color: "#FF006E",
  },
  {
    id: "3",
    title: "AI-Powered Chat Application",
    description: "Real-time chat with AI assistant integration",
    longDescription:
      "Modern chat application with AI-powered responses, real-time messaging using WebSockets, user authentication, and beautiful UI. Integrated with OpenAI API for intelligent conversations.",
    category: "Web Development",
    tags: ["AI", "WebSocket", "Real-time", "Chat"],
    technologies: [
      "React",
      "Socket.io",
      "Node.js",
      "OpenAI API",
      "PostgreSQL",
      "Redis",
    ],
    image: "/projects/chat-ai.jpg",
    liveUrl: "https://chat.example.com",
    githubUrl: "https://github.com/username/ai-chat",
    featured: false,
    year: 2023,
    role: "Full Stack Developer",
    duration: "2 months",
    color: "#8B5CF6",
  },
  {
    id: "4",
    title: "Mobile Fitness Tracker",
    description: "Cross-platform fitness tracking mobile application",
    longDescription:
      "Feature-rich fitness app with workout tracking, progress charts, meal planning, and social features. Built with React Native for iOS and Android.",
    category: "Mobile App",
    tags: ["React Native", "Fitness", "Health", "Mobile"],
    technologies: [
      "React Native",
      "Expo",
      "Firebase",
      "Redux",
      "React Native Paper",
    ],
    image: "/projects/fitness-app.jpg",
    liveUrl: "https://fitness.example.com",
    featured: false,
    year: 2023,
    client: "FitLife Corp",
    role: "Mobile Developer",
    duration: "3 months",
    achievements: [
      "50,000+ downloads",
      "4.8 star rating",
      "Featured on App Store",
    ],
    color: "#00FF41",
  },
  {
    id: "5",
    title: "Dashboard Analytics Platform",
    description: "Real-time analytics dashboard with data visualization",
    longDescription:
      "Enterprise-grade analytics platform with interactive charts, real-time data updates, customizable widgets, and export functionality. Handles millions of data points efficiently.",
    category: "Web Development",
    tags: ["Dashboard", "Analytics", "Data Viz", "Charts"],
    technologies: [
      "React",
      "D3.js",
      "Recharts",
      "Node.js",
      "PostgreSQL",
      "WebSocket",
    ],
    image: "/projects/dashboard.jpg",
    liveUrl: "https://dashboard.example.com",
    githubUrl: "https://github.com/username/dashboard",
    featured: false,
    year: 2023,
    client: "Data Insights Ltd",
    role: "Frontend Developer",
    duration: "5 months",
    color: "#FFFF00",
  },
  {
    id: "6",
    title: "3D Product Configurator",
    description: "Interactive 3D product customization tool",
    longDescription:
      "Web-based 3D configurator allowing customers to customize products in real-time. Features material changes, color selection, engraving preview, and AR view.",
    category: "3D Graphics",
    tags: ["Three.js", "3D", "Product", "AR"],
    technologies: [
      "Three.js",
      "React Three Fiber",
      "Next.js",
      "WebGL",
      "GLTF",
    ],
    image: "/projects/3d-configurator.jpg",
    liveUrl: "https://configurator.example.com",
    featured: true,
    year: 2024,
    client: "Luxury Brands Co",
    role: "3D Developer",
    duration: "4 months",
    achievements: [
      "40% increase in conversions",
      "Reduced return rate by 25%",
      "Award-winning UX",
    ],
    color: "#FF6B35",
  },
  {
    id: "7",
    title: "Social Media Management Tool",
    description: "Multi-platform social media scheduling and analytics",
    longDescription:
      "Comprehensive social media management platform supporting multiple accounts, scheduled posting, analytics tracking, and team collaboration features.",
    category: "Web Development",
    tags: ["SaaS", "Social Media", "Scheduling", "Analytics"],
    technologies: [
      "Next.js",
      "Node.js",
      "MongoDB",
      "Bull Queue",
      "Social APIs",
    ],
    image: "/projects/social-tool.jpg",
    liveUrl: "https://social.example.com",
    featured: false,
    year: 2023,
    role: "Full Stack Developer",
    duration: "6 months",
    color: "#FF006E",
  },
  {
    id: "8",
    title: "Portfolio Design System",
    description: "Comprehensive UI component library and design system",
    longDescription:
      "Production-ready component library with 100+ components, Storybook documentation, accessibility features, and theming support. Published as npm package.",
    category: "UI/UX Design",
    tags: ["Design System", "Components", "Storybook", "NPM"],
    technologies: [
      "React",
      "TypeScript",
      "Storybook",
      "Styled Components",
      "Rollup",
    ],
    image: "/projects/design-system.jpg",
    githubUrl: "https://github.com/username/design-system",
    featured: false,
    year: 2023,
    role: "UI Engineer",
    duration: "4 months",
    achievements: [
      "1000+ npm downloads/week",
      "Used by 10+ companies",
      "100% test coverage",
    ],
    color: "#8B5CF6",
  },
];

// Export filtered arrays for convenience
export const featuredProjects = projects.filter((p) => p.featured);
export const webProjects = projects.filter((p) => p.category === "Web Development");
export const mobileProjects = projects.filter((p) => p.category === "Mobile App");
export const graphicsProjects = projects.filter((p) => p.category === "3D Graphics");